export const actions = {
    profile: {
        "DATA_FETCHING": "PROFILE_DATA_FETCHING",
        "DATA_FETCHED": "PROFILE_DATA_FETCHED",
        "DATA_FETCH_ERROR": "PROFILE_DATA_FETCH_ERROR",
        "IMAGE_UPDATED": "PROFILE_IMAGE_UPDATED",
        "DATA_EDITED": "PROFILE_DATA_EDITED"
    },
    post: {
        "DATA_FETCHING": "POST_DATA_FETCHING",
        "DATA_FETCHED": "POST_DATA_FETCHED",
        "DATA_FETCH_ERROR": "POST_DATA_FETCH_ERROR",
        "DATA_CREATE": "POST_DATA_CREATE",
        "DATA_UPDATE": "POST_DATA_UPDATE",
        "DATA_DELETE": "POST_DATA_DELETE",
        "POST_COMMENT": "POST_COMMENT",
        "POST_DELETE_COMMENT": "POST_DELETE_COMMENT",
    }
}
